name: run tests
on: [push, pull_request]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
       with:
         fetch-depth: 1
     - run: |
         conda config --set always_yes yes --set changeps1 no
         conda update -q conda
     - run: |
         conda create -n tests
         conda install pycodestyle -n tests
         conda info -a
         conda list -n tests
     - run: |
         source /usr/share/miniconda/bin/activate tests
         pycodestyle --ignore=E501,W503 py21cmwedge
  test:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04] #, macos-latest]
        python-version: [2.7, 3.6, 3.7]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
      - run: |
          conda create -q -n tests python=$ ${{ matrix.python-version }} numpy scipy astropy nose pip
          conda install -c conda-forge healpy -n tests
      - run: |
          source /usr/share/miniconda/bin/activate tests
          nosetests py21cmwedge --with-coverage --cover-package=py21cmwedge
