name: Run Tests
on: [push, pull_request]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 1
     - uses: astral-sh/ruff-action@v3
       with:
         src: "./src"
  test:
    env:
      ENV_NAME: test
    name: Testing
    needs: Linter
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen --extra dev pytest
